// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddCandidateTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addCandidate() {
    // Test name: AddCandidate
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://opensource-demo.orangehrmlive.com//");
    // 2 | setWindowSize | 1366x728 | 
    driver.manage().window().setSize(new Dimension(1366, 728));
    // 3 | type | name=username | Admin
    driver.findElement(By.name("username")).sendKeys("Admin");
    // 4 | type | name=password | admin123
    driver.findElement(By.name("password")).sendKeys("admin123");
    // 5 | click | css=button.orangehrm-login-button | 
    driver.findElement(By.cssSelector("button.orangehrm-login-button")).click();
    // 6 | click | xpath=//span[text()='Recruitment']/ancestor::a | 
    driver.findElement(By.xpath("//span[text()=\'Recruitment\']/ancestor::a")).click();
    // 7 | click | css=button.oxd-button--secondary:nth-child(1) | 
    driver.findElement(By.cssSelector("button.oxd-button--secondary:nth-child(1)")).click();
    // 8 | type | name=firstName | Admin
    driver.findElement(By.name("firstName")).sendKeys("Admin");
    // 9 | type | name=lastName | MidaTest
    driver.findElement(By.name("lastName")).sendKeys("MidaTest");
    // 10 | type | xpath=(//input[@placeholder='Type here'])[1] | admin@gmail.com
    driver.findElement(By.xpath("(//input[@placeholder=\'Type here\'])[1]")).sendKeys("admin@gmail.com");
    // 11 | click | css=button.orangehrm-left-space | 
    driver.findElement(By.cssSelector("button.orangehrm-left-space")).click();
  }
}
